#/****************************************************************************
#
#    flow5 application
#    Copyright (C) 2025 André Deperrois 
#    All rights reserved.
#
#*****************************************************************************/



HEADERS += \
    $$PWD/boatedit/sailnurbsdlg.h \
    $$PWD/boatedit/sailoccdlg.h \
    $$PWD/boatedit/sailsplinedlg.h \
    $$PWD/boatedit/sailstldlg.h \
    $$PWD/boatedit/sailwingdlg.h \
    fl5/interfaces/editors/analysisseldlg.h \
    fl5/interfaces/editors/analysis2ddef/foilpolardlg.h \
    fl5/interfaces/editors/analysis2ddef/polarautonamedlg.h \
    fl5/interfaces/editors/analysis3ddef/aerodatadlg.h \
    fl5/interfaces/editors/analysis3ddef/btpolarautonamedlg.h \
    fl5/interfaces/editors/analysis3ddef/btpolardlg.h \
    fl5/interfaces/editors/analysis3ddef/btpolarnamemaker.h \
    fl5/interfaces/editors/analysis3ddef/ctrltablemodel.h \
    fl5/interfaces/editors/analysis3ddef/extradragdlg.h \
    fl5/interfaces/editors/analysis3ddef/extradragwt.h \
    fl5/interfaces/editors/analysis3ddef/planepolardlg.h \
    fl5/interfaces/editors/analysis3ddef/polar3ddlg.h \
    fl5/interfaces/editors/analysis3ddef/t123578polardlg.h \
    fl5/interfaces/editors/analysis3ddef/t6polardlg.h \
    fl5/interfaces/editors/analysis3ddef/wpolarautonamedlg.h \
    fl5/interfaces/editors/boatedit/boatdlg.h \
    fl5/interfaces/editors/boatedit/edgesplitdlg.h \
    fl5/interfaces/editors/boatedit/externalsaildlg.h \
    fl5/interfaces/editors/boatedit/thinsaildlg.h \
    fl5/interfaces/editors/boatedit/sailcadreaderdlg.h \
    fl5/interfaces/editors/boatedit/saildlg.h \
    fl5/interfaces/editors/boatedit/sailscaledlg.h \
    fl5/interfaces/editors/boatedit/sailsectionview.h \
    fl5/interfaces/editors/boatedit/wingsailsectiondelegate.h \
    fl5/interfaces/editors/boatedit/wingsailsectionmodel.h \
    fl5/interfaces/editors/editobjectdelegate.h \
    fl5/interfaces/editors/editplrdlg.h \
    fl5/interfaces/editors/foiledit/foil1splinedlg.h \
    fl5/interfaces/editors/foiledit/foil2splinedlg.h \
    fl5/interfaces/editors/foiledit/foilcamberdlg.h \
    fl5/interfaces/editors/foiledit/foilcoorddlg.h \
    fl5/interfaces/editors/foiledit/foildlg.h \
    fl5/interfaces/editors/foiledit/foilflapdlg.h \
    fl5/interfaces/editors/foiledit/foilledlg.h \
    fl5/interfaces/editors/foiledit/foilnacadlg.h \
    fl5/interfaces/editors/foiledit/foilnormalizedlg.h \
    fl5/interfaces/editors/foiledit/foilrepaneldlg.h \
    fl5/interfaces/editors/foiledit/foilscaledlg.h \
    fl5/interfaces/editors/foiledit/foiltegapdlg.h \
    fl5/interfaces/editors/foiledit/foilwt.h \
    fl5/interfaces/editors/foiledit/interpolatefoilsdlg.h \
    fl5/interfaces/editors/fuseedit/bodyscaledlg.h \
    fl5/interfaces/editors/fuseedit/bodytransdlg.h \
    fl5/interfaces/editors/fuseedit/flatfaceconverterdlg.h \
    fl5/interfaces/editors/fuseedit/fusedlg.h \
    fl5/interfaces/editors/fuseedit/fusemesherdlg.h \
    fl5/interfaces/editors/fuseedit/fuseoccdlg.h \
    fl5/interfaces/editors/fuseedit/fusestldlg.h \
    fl5/interfaces/editors/fuseedit/shapefixerdlg.h \
    fl5/interfaces/editors/fuseedit/xflfuseedit/fuseframewt.h \
    fl5/interfaces/editors/fuseedit/xflfuseedit/fuselinewt.h \
    fl5/interfaces/editors/fuseedit/xflfuseedit/fusexfldefdlg.h \
    fl5/interfaces/editors/fuseedit/xflfuseedit/fusexfldlg.h \
    fl5/interfaces/editors/fuseedit/xflfuseedit/fusexflobjectdlg.h \
    fl5/interfaces/editors/importobjectdlg.h \
    fl5/interfaces/editors/inertia/partinertiadelegate.h \
    fl5/interfaces/editors/inertia/partinertiadlg.h \
    fl5/interfaces/editors/inertia/partinertiamodel.h \
    fl5/interfaces/editors/inertia/planeinertiadlg.h \
    fl5/interfaces/editors/inertia/planeinertiamodel.h \
    fl5/interfaces/editors/inertia/planestlinertiadlg.h \
    fl5/interfaces/editors/inertia/planexflinertiadlg.h \
    fl5/interfaces/editors/inertia/pointmasstable.h \
    fl5/interfaces/editors/objecttreeview.h \
    fl5/interfaces/editors/planeedit/planedlg.h \
    fl5/interfaces/editors/planeedit/planepartdelegate.h \
    fl5/interfaces/editors/planeedit/planepartmodel.h \
    fl5/interfaces/editors/planeedit/planestldlg.h \
    fl5/interfaces/editors/planeedit/planexfldlg.h \
    fl5/interfaces/editors/rotatedlg.h \
    fl5/interfaces/editors/scaledlg.h \
    fl5/interfaces/editors/shapedlg.h \
    fl5/interfaces/editors/translatedlg.h \
    fl5/interfaces/editors/wingedit/wingdefdlg.h \
    fl5/interfaces/editors/wingedit/wingdlg.h \
    fl5/interfaces/editors/wingedit/wingobjectdlg.h \
    fl5/interfaces/editors/wingedit/wingscaledlg.h \
    fl5/interfaces/editors/wingedit/wingsectiondelegate.h \
    fl5/interfaces/editors/wingedit/wingsectionmodel.h \



SOURCES += \
    $$PWD/boatedit/sailnurbsdlg.cpp \
    $$PWD/boatedit/sailoccdlg.cpp \
    $$PWD/boatedit/sailsplinedlg.cpp \
    $$PWD/boatedit/sailstldlg.cpp \
    $$PWD/boatedit/sailwingdlg.cpp \
    fl5/interfaces/editors/analysis2ddef/foilpolardlg.cpp \
    fl5/interfaces/editors/analysis2ddef/polarautonamedlg.cpp \
    fl5/interfaces/editors/analysis3ddef/aerodatadlg.cpp \
    fl5/interfaces/editors/analysis3ddef/btpolarautonamedlg.cpp \
    fl5/interfaces/editors/analysis3ddef/btpolardlg.cpp \
    fl5/interfaces/editors/analysis3ddef/btpolarnamemaker.cpp \
    fl5/interfaces/editors/analysis3ddef/extradragdlg.cpp \
    fl5/interfaces/editors/analysis3ddef/extradragwt.cpp \
    fl5/interfaces/editors/analysis3ddef/planepolardlg.cpp \
    fl5/interfaces/editors/analysis3ddef/polar3ddlg.cpp \
    fl5/interfaces/editors/analysis3ddef/t123578polardlg.cpp \
    fl5/interfaces/editors/analysis3ddef/t6polardlg.cpp \
    fl5/interfaces/editors/analysis3ddef/wpolarautonamedlg.cpp \
    fl5/interfaces/editors/analysisseldlg.cpp \
    fl5/interfaces/editors/boatedit/boatdlg.cpp \
    fl5/interfaces/editors/boatedit/edgesplitdlg.cpp \
    fl5/interfaces/editors/boatedit/externalsaildlg.cpp \
    fl5/interfaces/editors/boatedit/thinsaildlg.cpp \
    fl5/interfaces/editors/boatedit/sailcadreaderdlg.cpp \
    fl5/interfaces/editors/boatedit/saildlg.cpp \
    fl5/interfaces/editors/boatedit/sailscaledlg.cpp \
    fl5/interfaces/editors/boatedit/sailsectionview.cpp \
    fl5/interfaces/editors/boatedit/wingsailsectiondelegate.cpp \
    fl5/interfaces/editors/boatedit/wingsailsectionmodel.cpp \
    fl5/interfaces/editors/editobjectdelegate.cpp \
    fl5/interfaces/editors/editplrdlg.cpp \
    fl5/interfaces/editors/foiledit/foil1splinedlg.cpp \
    fl5/interfaces/editors/foiledit/foil2splinedlg.cpp \
    fl5/interfaces/editors/foiledit/foilcamberdlg.cpp \
    fl5/interfaces/editors/foiledit/foilcoorddlg.cpp \
    fl5/interfaces/editors/foiledit/foildlg.cpp \
    fl5/interfaces/editors/foiledit/foilflapdlg.cpp \
    fl5/interfaces/editors/foiledit/foilledlg.cpp \
    fl5/interfaces/editors/foiledit/foilnacadlg.cpp \
    fl5/interfaces/editors/foiledit/foilnormalizedlg.cpp \
    fl5/interfaces/editors/foiledit/foilrepaneldlg.cpp \
    fl5/interfaces/editors/foiledit/foilscaledlg.cpp \
    fl5/interfaces/editors/foiledit/foiltegapdlg.cpp \
    fl5/interfaces/editors/foiledit/foilwt.cpp \
    fl5/interfaces/editors/foiledit/interpolatefoilsdlg.cpp \
    fl5/interfaces/editors/fuseedit/bodyscaledlg.cpp \
    fl5/interfaces/editors/fuseedit/bodytransdlg.cpp \
    fl5/interfaces/editors/fuseedit/flatfaceconverterdlg.cpp \
    fl5/interfaces/editors/fuseedit/fusedlg.cpp \
    fl5/interfaces/editors/fuseedit/fusemesherdlg.cpp \
    fl5/interfaces/editors/fuseedit/fuseoccdlg.cpp \
    fl5/interfaces/editors/fuseedit/fusestldlg.cpp \
    fl5/interfaces/editors/fuseedit/shapefixerdlg.cpp \
    fl5/interfaces/editors/fuseedit/xflfuseedit/fuseframewt.cpp \
    fl5/interfaces/editors/fuseedit/xflfuseedit/fuselinewt.cpp \
    fl5/interfaces/editors/fuseedit/xflfuseedit/fusexfldefdlg.cpp \
    fl5/interfaces/editors/fuseedit/xflfuseedit/fusexfldlg.cpp \
    fl5/interfaces/editors/fuseedit/xflfuseedit/fusexflobjectdlg.cpp \
    fl5/interfaces/editors/importobjectdlg.cpp \
    fl5/interfaces/editors/inertia/partinertiadelegate.cpp \
    fl5/interfaces/editors/inertia/partinertiadlg.cpp \
    fl5/interfaces/editors/inertia/partinertiamodel.cpp \
    fl5/interfaces/editors/inertia/planeinertiadlg.cpp \
    fl5/interfaces/editors/inertia/planeinertiamodel.cpp \
    fl5/interfaces/editors/inertia/planestlinertiadlg.cpp \
    fl5/interfaces/editors/inertia/planexflinertiadlg.cpp \
    fl5/interfaces/editors/inertia/pointmasstable.cpp \
    fl5/interfaces/editors/objecttreeview.cpp \
    fl5/interfaces/editors/planeedit/planedlg.cpp \
    fl5/interfaces/editors/planeedit/planepartdelegate.cpp \
    fl5/interfaces/editors/planeedit/planepartmodel.cpp \
    fl5/interfaces/editors/planeedit/planestldlg.cpp \
    fl5/interfaces/editors/planeedit/planexfldlg.cpp \
    fl5/interfaces/editors/rotatedlg.cpp \
    fl5/interfaces/editors/scaledlg.cpp \
    fl5/interfaces/editors/shapedlg.cpp \
    fl5/interfaces/editors/translatedlg.cpp \
    fl5/interfaces/editors/wingedit/wingdefdlg.cpp \
    fl5/interfaces/editors/wingedit/wingdlg.cpp \
    fl5/interfaces/editors/wingedit/wingobjectdlg.cpp \
    fl5/interfaces/editors/wingedit/wingscaledlg.cpp \
    fl5/interfaces/editors/wingedit/wingsectiondelegate.cpp \
    fl5/interfaces/editors/wingedit/wingsectionmodel.cpp \


