
HEADERS += \
    fl5/modules/xplane/analysis/analysis3dsettings.h \
    fl5/modules/xplane/analysis/batchplanedlg.h \
    fl5/modules/xplane/analysis/batchxmldlg.h \
    fl5/modules/xplane/analysis/lltanalysisdlg.h \
    fl5/modules/xplane/analysis/planeanalysisdlg.h \
    fl5/modules/xplane/analysis/streamlinemaker.h \
    fl5/modules/xplane/analysis/wpolarnamemaker.h \
    fl5/modules/xplane/controls/analysis3dctrls.h \
    fl5/modules/xplane/controls/planetreeview.h \
    fl5/modules/xplane/controls/popp3dctrls.h \
    fl5/modules/xplane/controls/stab3dctrls.h \
    fl5/modules/xplane/controls/stabtimectrls.h \
    fl5/modules/xplane/controls/targetcurvedlg.h \
    fl5/modules/xplane/controls/wingseldlg.h \
    fl5/modules/xplane/controls/xplanewt.h \
    fl5/modules/xplane/glview/gl3dxplaneview.h \
    fl5/modules/xplane/glview/glxplanebuffers.h \
    fl5/modules/xplane/graphs/cpgraphctrls.h \
    fl5/modules/xplane/graphs/cpviewwt.h \
    fl5/modules/xplane/graphs/poppgraphctrls.h \
    fl5/modules/xplane/graphs/xplanelegendwt.h \
    fl5/modules/xplane/menus/xplaneactions.h \
    fl5/modules/xplane/menus/xplanemenus.h \
    fl5/modules/xplane/xplane.h \

SOURCES += \
    fl5/modules/xplane/analysis/analysis3dsettings.cpp \
    fl5/modules/xplane/analysis/batchplanedlg.cpp \
    fl5/modules/xplane/analysis/batchxmldlg.cpp \
    fl5/modules/xplane/analysis/lltanalysisdlg.cpp \
    fl5/modules/xplane/analysis/planeanalysisdlg.cpp \
    fl5/modules/xplane/analysis/streamlinemaker.cpp \
    fl5/modules/xplane/analysis/wpolarnamemaker.cpp \
    fl5/modules/xplane/controls/analysis3dctrls.cpp \
    fl5/modules/xplane/controls/planetreeview.cpp \
    fl5/modules/xplane/controls/popp3dctrls.cpp \
    fl5/modules/xplane/controls/stab3dctrls.cpp \
    fl5/modules/xplane/controls/stabtimectrls.cpp \
    fl5/modules/xplane/controls/targetcurvedlg.cpp \
    fl5/modules/xplane/controls/wingseldlg.cpp \
    fl5/modules/xplane/controls/xplanewt.cpp \
    fl5/modules/xplane/glview/gl3dxplaneview.cpp \
    fl5/modules/xplane/glview/glxplanebuffers.cpp \
    fl5/modules/xplane/graphs/cpgraphctrls.cpp \
    fl5/modules/xplane/graphs/cpviewwt.cpp \
    fl5/modules/xplane/graphs/poppgraphctrls.cpp \
    fl5/modules/xplane/graphs/xplanelegendwt.cpp \
    fl5/modules/xplane/menus/xplaneactions.cpp \
    fl5/modules/xplane/menus/xplanemenus.cpp \
    fl5/modules/xplane/xplane.cpp \
