
HEADERS += \
    xflobjects/analysis3d/boattask.h \
    xflobjects/analysis3d/llttask.h \
    xflobjects/analysis3d/p3analysis.h \
    xflobjects/analysis3d/p3linanalysis.h \
    xflobjects/analysis3d/p3unianalysis.h \
    xflobjects/analysis3d/p4analysis.h \
    xflobjects/analysis3d/panelanalysis.h \
    xflobjects/analysis3d/planetask.h \
    xflobjects/analysis3d/streamlinemaker.h \
    xflobjects/analysis3d/task3d.h \
    xflobjects/exchange/cadexportdlg.h \
    xflobjects/exchange/stlwriterdlg.h \
    xflobjects/exchange/wingexportdlg.h \
    xflobjects/objects3d/analysis/aeroforces.h \
    xflobjects/objects3d/analysis/analysisseldlg.h \
    xflobjects/objects3d/analysis/boatopp.h \
    xflobjects/objects3d/analysis/boatpolar.h \
    xflobjects/objects3d/analysis/eigenvalues.h \
    xflobjects/objects3d/analysis/extradrag.h \
    xflobjects/objects3d/analysis/opp3d.h \
    xflobjects/objects3d/analysis/planeopp.h \
    xflobjects/objects3d/analysis/polar3d.h \
    xflobjects/objects3d/analysis/spandistribs.h \
    xflobjects/objects3d/analysis/stabderivatives.h \
    xflobjects/objects3d/analysis/wingopp.h \
    xflobjects/objects3d/analysis/wpolar.h \
    xflobjects/objects3d/analysis/wpolarext.h \
    xflobjects/objects3d/analysis/wpolarnamemaker.h \
    xflobjects/objects3d/fuse/fuse.h \
    xflobjects/objects3d/fuse/fuseflatfaces.h \
    xflobjects/objects3d/fuse/fusenurbs.h \
    xflobjects/objects3d/fuse/fuseocc.h \
    xflobjects/objects3d/fuse/fusesections.h \
    xflobjects/objects3d/fuse/fusestl.h \
    xflobjects/objects3d/fuse/fusexfl.h \
    xflobjects/objects3d/inertia/inertia.h \
    xflobjects/objects3d/inertia/pointmass.h \
    xflobjects/objects3d/objects3d.h \
    xflobjects/objects3d/part.h \
    xflobjects/objects3d/plane/plane.h \
    xflobjects/objects3d/plane/planestl.h \
    xflobjects/objects3d/plane/planexfl.h \
    xflobjects/objects3d/wing/surface.h \
    xflobjects/objects3d/wing/wingsection.h \
    xflobjects/objects3d/wing/wingxfl.h \
    xflobjects/objects_globals/anglecontrol.h \
    xflobjects/objects_globals/ctrlrange.h \
    xflobjects/objects_globals/fl5object.h \
    xflobjects/objects_globals/objects_global.h \
    xflobjects/objects_globals/objects_params.h \
    xflobjects/objects_globals/optstructures.h \
    xflobjects/sailobjects/boat.h \
    xflobjects/sailobjects/sailglobals.h \
    xflobjects/sailobjects/sailobjects.h \
    xflobjects/sailobjects/sails/externalsail.h \
    xflobjects/sailobjects/sails/nurbssail.h \
    xflobjects/sailobjects/sails/occsail.h \
    xflobjects/sailobjects/sails/sail.h \
    xflobjects/sailobjects/sails/splinesail.h \
    xflobjects/sailobjects/sails/stlsail.h \
    xflobjects/sailobjects/sails/wingsail.h \
    xflobjects/sailobjects/sails/wingsailsection.h \
    xflobjects/sailobjects/splines7/arcspline.h \
    xflobjects/sailobjects/splines7/naca4spline.h \
    xflobjects/sailobjects/splines7/s7spline.h \


SOURCES += \
    xflobjects/analysis3d/boattask.cpp \
    xflobjects/analysis3d/llttask.cpp \
    xflobjects/analysis3d/p3analysis.cpp \
    xflobjects/analysis3d/p3linanalysis.cpp \
    xflobjects/analysis3d/p3unianalysis.cpp \
    xflobjects/analysis3d/p4analysis.cpp \
    xflobjects/analysis3d/panelanalysis.cpp \
    xflobjects/analysis3d/planetask.cpp \
    xflobjects/analysis3d/streamlinemaker.cpp \
    xflobjects/analysis3d/task3d.cpp \
    xflobjects/exchange/cadexportdlg.cpp \
    xflobjects/exchange/stlwriterdlg.cpp \
    xflobjects/exchange/wingexportdlg.cpp \
    xflobjects/objects3d/analysis/aeroforces.cpp \
    xflobjects/objects3d/analysis/analysisseldlg.cpp \
    xflobjects/objects3d/analysis/boatopp.cpp \
    xflobjects/objects3d/analysis/boatpolar.cpp \
    xflobjects/objects3d/analysis/opp3d.cpp \
    xflobjects/objects3d/analysis/planeopp.cpp \
    xflobjects/objects3d/analysis/polar3d.cpp \
    xflobjects/objects3d/analysis/spandistribs.cpp \
    xflobjects/objects3d/analysis/stabderivatives.cpp \
    xflobjects/objects3d/analysis/wingopp.cpp \
    xflobjects/objects3d/analysis/wpolar.cpp \
    xflobjects/objects3d/analysis/wpolarext.cpp \
    xflobjects/objects3d/analysis/wpolarnamemaker.cpp \
    xflobjects/objects3d/fuse/fuse.cpp \
    xflobjects/objects3d/fuse/fuseflatfaces.cpp \
    xflobjects/objects3d/fuse/fusenurbs.cpp \
    xflobjects/objects3d/fuse/fuseocc.cpp \
    xflobjects/objects3d/fuse/fusesections.cpp \
    xflobjects/objects3d/fuse/fusestl.cpp \
    xflobjects/objects3d/fuse/fusexfl.cpp \
    xflobjects/objects3d/inertia/inertia.cpp \
    xflobjects/objects3d/objects3d.cpp \
    xflobjects/objects3d/part.cpp \
    xflobjects/objects3d/plane/plane.cpp \
    xflobjects/objects3d/plane/planestl.cpp \
    xflobjects/objects3d/plane/planexfl.cpp \
    xflobjects/objects3d/wing/surface.cpp \
    xflobjects/objects3d/wing/wingsection.cpp \
    xflobjects/objects3d/wing/wingxfl.cpp \
    xflobjects/objects_globals/objects_global.cpp \
    xflobjects/sailobjects/boat.cpp \
    xflobjects/sailobjects/sailglobals.cpp \
    xflobjects/sailobjects/sailobjects.cpp \
    xflobjects/sailobjects/sails/externalsail.cpp \
    xflobjects/sailobjects/sails/nurbssail.cpp \
    xflobjects/sailobjects/sails/occsail.cpp \
    xflobjects/sailobjects/sails/sail.cpp \
    xflobjects/sailobjects/sails/splinesail.cpp \
    xflobjects/sailobjects/sails/stlsail.cpp \
    xflobjects/sailobjects/sails/wingsail.cpp \
    xflobjects/sailobjects/sails/wingsailsection.cpp \
    xflobjects/sailobjects/splines7/arcspline.cpp \
    xflobjects/sailobjects/splines7/naca4spline.cpp \
    xflobjects/sailobjects/splines7/s7spline.cpp \
