#/****************************************************************************
#
#    flow5 application
#    Copyright (C) Andre Deperrois 
#    All rights reserved.
#
#*****************************************************************************/


RESOURCES += \
    xfl/resources/qss.qrc \
    xfl/resources/icons.qrc \
    xfl/resources/images.qrc \
    xfl/resources/sailimages.qrc


HEADERS += \
    xfl/controls/analysisrangetable.h \
    xfl/controls/crossflowctrls.h \
    xfl/controls/flowctrls.h \
    xfl/controls/opp3dscalesctrls.h \
    xfl/controls/streamlinesctrls.h \
    xfl/controls/t8rangetable.h \
    xfl/controls/w3dprefs.h \
    xfl/editors/analysis2ddef/foilpolardlg.h \
    xfl/editors/analysis2ddef/polarautonamedlg.h \
    xfl/editors/analysis3ddef/aerodatadlg.h \
    xfl/editors/analysis3ddef/btpolarautonamedlg.h \
    xfl/editors/analysis3ddef/btpolardlg.h \
    xfl/editors/analysis3ddef/btpolarnamemaker.h \
    xfl/editors/analysis3ddef/ctrltablemodel.h \
    xfl/editors/analysis3ddef/extradragdlg.h \
    xfl/editors/analysis3ddef/extradragwt.h \
    xfl/editors/analysis3ddef/planepolardlg.h \
    xfl/editors/analysis3ddef/polar3ddlg.h \
    xfl/editors/analysis3ddef/t123578polardlg.h \
    xfl/editors/analysis3ddef/t6polardlg.h \
    xfl/editors/analysis3ddef/wpolarautonamedlg.h \
    xfl/editors/boatedit/boatdlg.h \
    xfl/editors/boatedit/externalsaildlg.h \
    xfl/editors/boatedit/nurbssaildlg.h \
    xfl/editors/boatedit/occsaildlg.h \
    xfl/editors/boatedit/sailcadreaderdlg.h \
    xfl/editors/boatedit/saildlg.h \
    xfl/editors/boatedit/sailscaledlg.h \
    xfl/editors/boatedit/sailsectionview.h \
    xfl/editors/boatedit/splinesaildlg.h \
    xfl/editors/boatedit/stlsaildlg.h \
    xfl/editors/boatedit/wingsaildlg.h \
    xfl/editors/boatedit/wingsailsectiondelegate.h \
    xfl/editors/boatedit/wingsailsectionmodel.h \
    xfl/editors/edgesplitdlg.h \
    xfl/editors/editobjectdelegate.h \
    xfl/editors/editplrdlg.h \
    xfl/editors/fuseedit/bodyscaledlg.h \
    xfl/editors/fuseedit/bodytransdlg.h \
    xfl/editors/fuseedit/flatfaceconverterdlg.h \
    xfl/editors/fuseedit/fusedlg.h \
    xfl/editors/fuseedit/fusemesherdlg.h \
    xfl/editors/fuseedit/fuseoccdlg.h \
    xfl/editors/fuseedit/fusestldlg.h \
    xfl/editors/fuseedit/shapefixerdlg.h \
    xfl/editors/fuseedit/xflfuseedit/fuseframewt.h \
    xfl/editors/fuseedit/xflfuseedit/fuselinewt.h \
    xfl/editors/fuseedit/xflfuseedit/fusexfldefdlg.h \
    xfl/editors/fuseedit/xflfuseedit/fusexfldlg.h \
    xfl/editors/fuseedit/xflfuseedit/fusexflobjectdlg.h \
    xfl/editors/importobjectdlg.h \
    xfl/editors/inertia/partinertiadelegate.h \
    xfl/editors/inertia/partinertiadlg.h \
    xfl/editors/inertia/partinertiamodel.h \
    xfl/editors/inertia/planeinertiadlg.h \
    xfl/editors/inertia/planeinertiamodel.h \
    xfl/editors/inertia/planestlinertiadlg.h \
    xfl/editors/inertia/planexflinertiadlg.h \
    xfl/editors/inertia/pointmasstable.h \
    xfl/editors/objecttreeview.h \
    xfl/editors/planeedit/planedlg.h \
    xfl/editors/planeedit/planepartdelegate.h \
    xfl/editors/planeedit/planepartmodel.h \
    xfl/editors/planeedit/planestldlg.h \
    xfl/editors/planeedit/planexfldlg.h \
    xfl/editors/rotatedlg.h \
    xfl/editors/scaledlg.h \
    xfl/editors/shapedlg.h \
    xfl/editors/translatedlg.h \
    xfl/editors/wingedit/wingdefdlg.h \
    xfl/editors/wingedit/wingdlg.h \
    xfl/editors/wingedit/wingobjectdlg.h \
    xfl/editors/wingedit/wingscaledlg.h \
    xfl/editors/wingedit/wingsectiondelegate.h \
    xfl/editors/wingedit/wingsectionmodel.h \
    xfl/globals/fileio.h \
    xfl/globals/flow5.h \
    xfl/globals/gui_params.h \
    xfl/globals/mainframe.h \
    xfl/graphs/cpgraphctrls.h \
    xfl/graphs/cpviewwt.h \
    xfl/graphs/graphtilectrls.h \
    xfl/graphs/graphtiles.h \
    xfl/misc/aboutf5.h \
    xfl/misc/creditsdlg.h \
    xfl/opengl/gl3dboatview.h \
    xfl/opengl/gl3dfuseview.h \
    xfl/opengl/gl3dgeomcontrols.h \
    xfl/opengl/gl3doptimxflview.h \
    xfl/opengl/gl3dparetoview.h \
    xfl/opengl/gl3dplanestlview.h \
    xfl/opengl/gl3dplanexflview.h \
    xfl/opengl/gl3dsailview.h \
    xfl/opengl/gl3dshapesview.h \
    xfl/opengl/gl3dshapeview.h \
    xfl/opengl/gl3dwingview.h \
    xfl/opengl/gl3dxflview.h \
    xfl/opengl/gl_occ.h \
    xfl/opengl/gl_xfl.h \
    xfl/options/prefsdlg.h \
    xfl/options/saveoptionswt.h \
    xfl/options/unitswt.h \
    xfl/test/attractor2d.h \
    xfl/test/onevortontestdlg.h \
    xfl/test/panel3testdlg.h \
    xfl/test/panelanalysistest.h \
    xfl/test/rupperttestdlg.h \
    xfl/test/test3d/gl3daxesview.h \
    xfl/test/test3d/gl3dcontourview.h \
    xfl/test/test3d/gl3dflightview.h \
    xfl/test/test3d/gl3doptim2d.h \
    xfl/test/test3d/gl3dpanelfield.h \
    xfl/test/test3d/gl3dquadfield.h \
    xfl/test/test3d/gl3dsingularity.h \
    xfl/test/test3d/gl3dsurfaceplot.h \
    xfl/test/test3d/gl3dvortonfield.h \
    xfl/test/textoutputtestdlg.h \
    xfl/test/vortontestdlg.h \
    xfl/xdirect/analysis/analysis2dsettings.h \
    xfl/xdirect/analysis/xfoilanalysisdlg.h \
    xfl/xdirect/analysis/xfoilbatchdlg.h \
    xfl/xdirect/controls/analysis2dctrls.h \
    xfl/xdirect/controls/foiltabledelegate.h \
    xfl/xdirect/controls/foiltableview.h \
    xfl/xdirect/controls/foiltreeview.h \
    xfl/xdirect/controls/lecircledlg.h \
    xfl/xdirect/controls/oppointctrls.h \
    xfl/xdirect/graphs/blgraphctrls.h \
    xfl/xdirect/graphs/xdirectlegendwt.h \
    xfl/xdirect/menus/xdirectactions.h \
    xfl/xdirect/menus/xdirectmenus.h \
    xfl/xdirect/mgt/foilplrlistdlg.h \
    xfl/xdirect/view2d/dfoillegendwt.h \
    xfl/xdirect/view2d/dfoilwt.h \
    xfl/xdirect/view2d/oppointwt.h \
    xfl/xdirect/xdirect.h \
    xfl/xplane/analysis/analysis3dsettings.h \
    xfl/xplane/analysis/batchplanedlg.h \
    xfl/xplane/analysis/batchxmldlg.h \
    xfl/xplane/analysis/lltanalysisdlg.h \
    xfl/xplane/analysis/planeanalysisdlg.h \
    xfl/xplane/controls/analysis3dctrls.h \
    xfl/xplane/controls/planetreeview.h \
    xfl/xplane/controls/popp3dctrls.h \
    xfl/xplane/controls/stab3dctrls.h \
    xfl/xplane/controls/stabtimectrls.h \
    xfl/xplane/controls/targetcurvedlg.h \
    xfl/xplane/controls/wingseldlg.h \
    xfl/xplane/controls/xplanewt.h \
    xfl/xplane/glview/gl3dxplaneview.h \
    xfl/xplane/glview/glxplanebuffers.h \
    xfl/xplane/graphs/poppgraphctrls.h \
    xfl/xplane/graphs/xplanelegendwt.h \
    xfl/xplane/menus/xplaneactions.h \
    xfl/xplane/menus/xplanemenus.h \
    xfl/xplane/xplane.h \
    xfl/xsail/analysis/boatanalysisdlg.h \
    xfl/xsail/controls/boattreeview.h \
    xfl/xsail/controls/gl3dxsailctrls.h \
    xfl/xsail/controls/xsailanalysisctrls.h \
    xfl/xsail/controls/xsaildisplayctrls.h \
    xfl/xsail/menus/xsailactions.h \
    xfl/xsail/menus/xsailmenus.h \
    xfl/xsail/view/gl3dxsailview.h \
    xfl/xsail/view/xsaillegendwt.h \
    xfl/xsail/xsail.h \



SOURCES += \
    xfl/controls/analysisrangetable.cpp \
    xfl/controls/crossflowctrls.cpp \
    xfl/controls/flowctrls.cpp \
    xfl/controls/opp3dscalesctrls.cpp \
    xfl/controls/streamlinesctrls.cpp \
    xfl/controls/t8rangetable.cpp \
    xfl/controls/w3dprefs.cpp \
    xfl/editors/analysis2ddef/foilpolardlg.cpp \
    xfl/editors/analysis2ddef/polarautonamedlg.cpp \
    xfl/editors/analysis3ddef/aerodatadlg.cpp \
    xfl/editors/analysis3ddef/btpolarautonamedlg.cpp \
    xfl/editors/analysis3ddef/btpolardlg.cpp \
    xfl/editors/analysis3ddef/btpolarnamemaker.cpp \
    xfl/editors/analysis3ddef/extradragdlg.cpp \
    xfl/editors/analysis3ddef/extradragwt.cpp \
    xfl/editors/analysis3ddef/planepolardlg.cpp \
    xfl/editors/analysis3ddef/polar3ddlg.cpp \
    xfl/editors/analysis3ddef/t123578polardlg.cpp \
    xfl/editors/analysis3ddef/t6polardlg.cpp \
    xfl/editors/analysis3ddef/wpolarautonamedlg.cpp \
    xfl/editors/boatedit/boatdlg.cpp \
    xfl/editors/boatedit/externalsaildlg.cpp \
    xfl/editors/boatedit/nurbssaildlg.cpp \
    xfl/editors/boatedit/occsaildlg.cpp \
    xfl/editors/boatedit/sailcadreaderdlg.cpp \
    xfl/editors/boatedit/saildlg.cpp \
    xfl/editors/boatedit/sailscaledlg.cpp \
    xfl/editors/boatedit/sailsectionview.cpp \
    xfl/editors/boatedit/splinesaildlg.cpp \
    xfl/editors/boatedit/stlsaildlg.cpp \
    xfl/editors/boatedit/wingsaildlg.cpp \
    xfl/editors/boatedit/wingsailsectiondelegate.cpp \
    xfl/editors/boatedit/wingsailsectionmodel.cpp \
    xfl/editors/edgesplitdlg.cpp \
    xfl/editors/editobjectdelegate.cpp \
    xfl/editors/editplrdlg.cpp \
    xfl/editors/fuseedit/bodyscaledlg.cpp \
    xfl/editors/fuseedit/bodytransdlg.cpp \
    xfl/editors/fuseedit/flatfaceconverterdlg.cpp \
    xfl/editors/fuseedit/fusedlg.cpp \
    xfl/editors/fuseedit/fusemesherdlg.cpp \
    xfl/editors/fuseedit/fuseoccdlg.cpp \
    xfl/editors/fuseedit/fusestldlg.cpp \
    xfl/editors/fuseedit/shapefixerdlg.cpp \
    xfl/editors/fuseedit/xflfuseedit/fuseframewt.cpp \
    xfl/editors/fuseedit/xflfuseedit/fuselinewt.cpp \
    xfl/editors/fuseedit/xflfuseedit/fusexfldefdlg.cpp \
    xfl/editors/fuseedit/xflfuseedit/fusexfldlg.cpp \
    xfl/editors/fuseedit/xflfuseedit/fusexflobjectdlg.cpp \
    xfl/editors/importobjectdlg.cpp \
    xfl/editors/inertia/partinertiadelegate.cpp \
    xfl/editors/inertia/partinertiadlg.cpp \
    xfl/editors/inertia/partinertiamodel.cpp \
    xfl/editors/inertia/planeinertiadlg.cpp \
    xfl/editors/inertia/planeinertiamodel.cpp \
    xfl/editors/inertia/planestlinertiadlg.cpp \
    xfl/editors/inertia/planexflinertiadlg.cpp \
    xfl/editors/inertia/pointmasstable.cpp \
    xfl/editors/objecttreeview.cpp \
    xfl/editors/planeedit/planedlg.cpp \
    xfl/editors/planeedit/planepartdelegate.cpp \
    xfl/editors/planeedit/planepartmodel.cpp \
    xfl/editors/planeedit/planestldlg.cpp \
    xfl/editors/planeedit/planexfldlg.cpp \
    xfl/editors/rotatedlg.cpp \
    xfl/editors/scaledlg.cpp \
    xfl/editors/shapedlg.cpp \
    xfl/editors/translatedlg.cpp \
    xfl/editors/wingedit/wingdefdlg.cpp \
    xfl/editors/wingedit/wingdlg.cpp \
    xfl/editors/wingedit/wingobjectdlg.cpp \
    xfl/editors/wingedit/wingscaledlg.cpp \
    xfl/editors/wingedit/wingsectiondelegate.cpp \
    xfl/editors/wingedit/wingsectionmodel.cpp \
    xfl/globals/fileio.cpp \
    xfl/globals/flow5.cpp \
    xfl/globals/main.cpp \
    xfl/globals/mainframe.cpp \
    xfl/graphs/cpgraphctrls.cpp \
    xfl/graphs/cpviewwt.cpp \
    xfl/graphs/graphtilectrls.cpp \
    xfl/graphs/graphtiles.cpp \
    xfl/misc/aboutf5.cpp \
    xfl/misc/creditsdlg.cpp \
    xfl/opengl/gl3dboatview.cpp \
    xfl/opengl/gl3dfuseview.cpp \
    xfl/opengl/gl3dgeomcontrols.cpp \
    xfl/opengl/gl3doptimxflview.cpp \
    xfl/opengl/gl3dparetoview.cpp \
    xfl/opengl/gl3dplanestlview.cpp \
    xfl/opengl/gl3dplanexflview.cpp \
    xfl/opengl/gl3dsailview.cpp \
    xfl/opengl/gl3dshapesview.cpp \
    xfl/opengl/gl3dshapeview.cpp \
    xfl/opengl/gl3dwingview.cpp \
    xfl/opengl/gl3dxflview.cpp \
    xfl/opengl/gl_occ.cpp \
    xfl/opengl/gl_xfl.cpp \
    xfl/options/prefsdlg.cpp \
    xfl/options/saveoptionswt.cpp \
    xfl/options/unitswt.cpp \
    xfl/test/attractor2d.cpp \
    xfl/test/onevortontestdlg.cpp \
    xfl/test/panel3testdlg.cpp \
    xfl/test/panelanalysistest.cpp \
    xfl/test/rupperttestdlg.cpp \
    xfl/test/test3d/gl3daxesview.cpp \
    xfl/test/test3d/gl3dcontourview.cpp \
    xfl/test/test3d/gl3dflightview.cpp \
    xfl/test/test3d/gl3doptim2d.cpp \
    xfl/test/test3d/gl3dpanelfield.cpp \
    xfl/test/test3d/gl3dquadfield.cpp \
    xfl/test/test3d/gl3dsingularity.cpp \
    xfl/test/test3d/gl3dsurfaceplot.cpp \
    xfl/test/test3d/gl3dvortonfield.cpp \
    xfl/test/textoutputtestdlg.cpp \
    xfl/test/vortontestdlg.cpp \
    xfl/xdirect/analysis/analysis2dsettings.cpp \
    xfl/xdirect/analysis/xfoilanalysisdlg.cpp \
    xfl/xdirect/analysis/xfoilbatchdlg.cpp \
    xfl/xdirect/controls/analysis2dctrls.cpp \
    xfl/xdirect/controls/foiltabledelegate.cpp \
    xfl/xdirect/controls/foiltableview.cpp \
    xfl/xdirect/controls/foiltreeview.cpp \
    xfl/xdirect/controls/lecircledlg.cpp \
    xfl/xdirect/controls/oppointctrls.cpp \
    xfl/xdirect/graphs/blgraphctrls.cpp \
    xfl/xdirect/graphs/xdirectlegendwt.cpp \
    xfl/xdirect/menus/xdirectactions.cpp \
    xfl/xdirect/menus/xdirectmenus.cpp \
    xfl/xdirect/mgt/foilplrlistdlg.cpp \
    xfl/xdirect/view2d/dfoillegendwt.cpp \
    xfl/xdirect/view2d/dfoilwt.cpp \
    xfl/xdirect/view2d/oppointwt.cpp \
    xfl/xdirect/xdirect.cpp \
    xfl/xplane/analysis/analysis3dsettings.cpp \
    xfl/xplane/analysis/batchplanedlg.cpp \
    xfl/xplane/analysis/batchxmldlg.cpp \
    xfl/xplane/analysis/lltanalysisdlg.cpp \
    xfl/xplane/analysis/planeanalysisdlg.cpp \
    xfl/xplane/controls/analysis3dctrls.cpp \
    xfl/xplane/controls/planetreeview.cpp \
    xfl/xplane/controls/popp3dctrls.cpp \
    xfl/xplane/controls/stab3dctrls.cpp \
    xfl/xplane/controls/stabtimectrls.cpp \
    xfl/xplane/controls/targetcurvedlg.cpp \
    xfl/xplane/controls/wingseldlg.cpp \
    xfl/xplane/controls/xplanewt.cpp \
    xfl/xplane/glview/gl3dxplaneview.cpp \
    xfl/xplane/glview/glxplanebuffers.cpp \
    xfl/xplane/graphs/poppgraphctrls.cpp \
    xfl/xplane/graphs/xplanelegendwt.cpp \
    xfl/xplane/menus/xplaneactions.cpp \
    xfl/xplane/menus/xplanemenus.cpp \
    xfl/xplane/xplane.cpp \
    xfl/xsail/analysis/boatanalysisdlg.cpp \
    xfl/xsail/controls/boattreeview.cpp \
    xfl/xsail/controls/gl3dxsailctrls.cpp \
    xfl/xsail/controls/xsailanalysisctrls.cpp \
    xfl/xsail/controls/xsaildisplayctrls.cpp \
    xfl/xsail/menus/xsailactions.cpp \
    xfl/xsail/menus/xsailmenus.cpp \
    xfl/xsail/view/gl3dxsailview.cpp \
    xfl/xsail/view/xsaillegendwt.cpp \
    xfl/xsail/xsail.cpp \



